Finally fixed dev build detection!

diff --git a/.github/workflows/deploy-to-s3.yml b/.github/workflows/deploy-to-s3.yml
--- a/.github/workflows/deploy-to-s3.yml
+++ b/.github/workflows/deploy-to-s3.yml
@@ -33,11 +33,9 @@ jobs:
         uses: actions/checkout@v4
       - name: "Abort if any trace of development build is detected (it should be a staging build)."
         run: |
-          num_occurrences=$((grep -r 'testttt' * || true) | wc -l)
+          num_occurrences=$((grep -r 'localhost:1313' * || true) | wc -l)
           if [ "$num_occurrences" -gt "0" ]; then
-            echo "num_occurrences: $num_occurrences"
-          else
-            echo "no occurrences"
+            echo "::error::Development build detected. To fix this, commit to public dir/repo after issuing 'hugo -e staging' command."
           fi
       - name: "Replace 'staging' Google tags with 'production' equivalents"
         run: find . -type f -exec sed -i~ 's/B3ECKP96EL/DPHXLK5VEW/g' '{}' '+'
