Readding grep to dev build check.

diff --git a/.github/workflows/deploy-to-s3.yml b/.github/workflows/deploy-to-s3.yml
--- a/.github/workflows/deploy-to-s3.yml
+++ b/.github/workflows/deploy-to-s3.yml
@@ -33,7 +33,7 @@ jobs:
         uses: actions/checkout@v4
       - name: "Abort if any trace of development build is detected (it should be a staging build)."
         run: |
-          echo "::error::Development build detected." >&2
+          [grep -qr 'localhost:1313' * ] && echo "::error::Development build detected." && exit 1
       - name: "Replace 'staging' Google tags with 'production' equivalents"
         run: find . -type f -exec sed -i~ 's/B3ECKP96EL/DPHXLK5VEW/g' '{}' '+'
       - name: "Replace 'staging' URL with 'production' equivalent"
